name: "Terraform Destroy Pipeline v1"
on:
  workflow_dispatch:
    
jobs:
 
  terraform-lb-apply:
    name: "Destroy LB"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
        with:
          ref: main        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          terraform_wrapper: false
          
      - name: Terraform Init
        id: init1
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AZURE_BACKEND_KEY }}" 

      - name: Terraform Destroy
        id: destroy1
        run: terraform destroy -auto-approve -no-color -input=false
        env:
          VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}