name: "Terraform Pipeline v1.37"
on:
  push:
    branches:
      - main

jobs:
 
  terraform-lb-apply:
    name: "Test & Apply LB"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
        with:
          ref: main        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          
      - name: Terraform Init
        id: init1
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AZURE_BACKEND_KEY }}" 

      - name: Terraform Apply
        id: apply1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color -input=false
        env:
          VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}
          # TF_LOG: debug 

      - name: Terraform Output
        id: output
        run: |
          output_value=$(terraform output -raw domain | tr -d '\n' | tr -d '%')
          echo "TERRAFORM_OUTPUT=$output_value" >> $GITHUB_ENV

      - name: Wait For LB Creation
        run: |  
          sleep 10

      - name: Record Start Timestamp
        run: |
          echo "TF_VAR_timestamp_start=$(date +%s)" >> $GITHUB_ENV

      - name: Run Application Tests
        run: |
          sleep 5
            curl --location https://$TERRAFORM_OUTPUT/api/sentence \
            --header 'Authorization: APIToken unkPPvEXl9Np1DJRR4UvQpK9DoI=' \
            --header 'Cookie: 3cac5=1668691945832-613485146; a5245=1691663394617-230291457; bcda5=1694434085538-116933348; c4295=1668693291780-467940678; a52403=WhfZxNqVqB3+Hdqr0Z7j9qyf9yCT7iupzf/NbPUXnMlC8QlkypjTodFTULQ+wayVeVmj4CJpYbH6JXVz5491ZhGd60jS8BorOVxNLjcRxPDiFDAnn+NSbYpV57NSRR6O/49MkfBY5syPeP0GW2H+Ndtde/E7Rzex/iOFib2jZC/4p7xv'
            curl --location https://$TERRAFORM_OUTPUT/api/backgrounds/6 \
            --header 'Authorization: APIToken unkPPvEXl9Np1DJRR4UvQpK9DoI=' \
            --header 'Cookie: 3cac5=1668691945832-613485146; a5245=1691663394617-230291457; bcda5=1694434085538-116933348; c4295=1668693291780-467940678; a52403=WhfZxNqVqB3+Hdqr0Z7j9qyf9yCT7iupzf/NbPUXnMlC8QlkypjTodFTULQ+wayVeVmj4CJpYbH6JXVz5491ZhGd60jS8BorOVxNLjcRxPDiFDAnn+NSbYpV57NSRR6O/49MkfBY5syPeP0GW2H+Ndtde/E7Rzex/iOFib2jZC/4p7xv'
            curl --location https://$TERRAFORM_OUTPUT/images/nginx.png \
            --header 'Authorization: APIToken unkPPvEXl9Np1DJRR4UvQpK9DoI=' \
            --header 'Cookie: 3cac5=1668691945832-613485146; a5245=1691663394617-230291457; bcda5=1694434085538-116933348; c4295=1668693291780-467940678; a52403=WhfZxNqVqB3+Hdqr0Z7j9qyf9yCT7iupzf/NbPUXnMlC8QlkypjTodFTULQ+wayVeVmj4CJpYbH6JXVz5491ZhGd60jS8BorOVxNLjcRxPDiFDAnn+NSbYpV57NSRR6O/49MkfBY5syPeP0GW2H+Ndtde/E7Rzex/iOFib2jZC/4p7xv'
            curl --location https://$TERRAFORM_OUTPUT/images/f5.png \
            --header 'Authorization: APIToken unkPPvEXl9Np1DJRR4UvQpK9DoI=' \
            --header 'Cookie: 3cac5=1668691945832-613485146; a5245=1691663394617-230291457; bcda5=1694434085538-116933348; c4295=1668693291780-467940678; a52403=WhfZxNqVqB3+Hdqr0Z7j9qyf9yCT7iupzf/NbPUXnMlC8QlkypjTodFTULQ+wayVeVmj4CJpYbH6JXVz5491ZhGd60jS8BorOVxNLjcRxPDiFDAnn+NSbYpV57NSRR6O/49MkfBY5syPeP0GW2H+Ndtde/E7Rzex/iOFib2jZC/4p7xv'        
          sleep 5
        continue-on-error: true

      - name: Record End Timestamp
        run: |  
          echo "TF_VAR_timestamp_end=$(date +%s)" >> $GITHUB_ENV